{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "a1bc1641-b600-4fb7-a1bd-c5320a4d9021",
   "metadata": {},
   "outputs": [],
   "source": [
    "# ===============================\n",
    "# 1. Imports & Logging Setup\n",
    "# ===============================\n",
    "import warnings\n",
    "import logging\n",
    "warnings.filterwarnings('ignore')\n",
    "logging.getLogger(\"neuralprophet\").setLevel(logging.ERROR)\n",
    "logging.getLogger(\"NP\").setLevel(logging.ERROR)\n",
    "\n",
    "import pandas as pd\n",
    "import plotly.express as px\n",
    "import plotly.graph_objects as go\n",
    "from dash import Dash, dcc, html, Input, Output, State\n",
    "from neuralprophet import NeuralProphet\n",
    "\n",
    "# ===============================\n",
    "# 2. Load & Preprocess Data\n",
    "# ===============================\n",
    "df = pd.read_csv(\"Global_Superstore2.csv\", encoding=\"ISO-8859-1\")\n",
    "df[\"Order Date\"] = pd.to_datetime(df[\"Order Date\"])\n",
    "df.columns = [c.strip().replace(\" \", \"_\") for c in df.columns]\n",
    "\n",
    "# Aggregate monthly total sales for global model\n",
    "monthly_sales = df.groupby(pd.Grouper(key=\"Order_Date\", freq=\"MS\"))[[\"Sales\"]].sum().reset_index()\n",
    "monthly_sales.columns = [\"ds\", \"y\"]\n",
    "\n",
    "# ===============================\n",
    "# 3. Fit Single Global NeuralProphet Model\n",
    "# ===============================\n",
    "m = NeuralProphet(\n",
    "    yearly_seasonality=True,\n",
    "    weekly_seasonality=False,\n",
    "    daily_seasonality=False,\n",
    "    epochs=50,\n",
    "    learning_rate=1.0\n",
    ")\n",
    "m.fit(monthly_sales, freq=\"MS\", checkpointing=False)\n",
    "\n",
    "# Precompute global forecast (max 24 months ahead)\n",
    "future = m.make_future_dataframe(monthly_sales, periods=24)\n",
    "global_forecast = m.predict(future)\n",
    "\n",
    "# ===============================\n",
    "# 4. Dash App Layout\n",
    "# ===============================\n",
    "app = Dash(__name__)\n",
    "\n",
    "app.layout = html.Div([\n",
    "    html.H1(\"📊 Global Superstore Dashboard\", style={\"textAlign\": \"center\"}),\n",
    "\n",
    "    # Filters\n",
    "    html.Div([\n",
    "        html.Div([\n",
    "            html.Label(\"Select Region:\"),\n",
    "            dcc.Dropdown(\n",
    "                id=\"region-filter\",\n",
    "                options=[{\"label\": r, \"value\": r} for r in df[\"Region\"].unique()],\n",
    "                value=None,\n",
    "                placeholder=\"All Regions\"\n",
    "            )\n",
    "        ], style={\"width\": \"24%\", \"display\": \"inline-block\", \"marginRight\": \"1%\"}),\n",
    "\n",
    "        html.Div([\n",
    "            html.Label(\"Select Category:\"),\n",
    "            dcc.Dropdown(\n",
    "                id=\"category-filter\",\n",
    "                options=[{\"label\": c, \"value\": c} for c in df[\"Category\"].unique()],\n",
    "                value=None,\n",
    "                placeholder=\"All Categories\"\n",
    "            )\n",
    "        ], style={\"width\": \"24%\", \"display\": \"inline-block\", \"marginRight\": \"1%\"}),\n",
    "\n",
    "        html.Div([\n",
    "            html.Label(\"Forecast Horizon (months):\"),\n",
    "            dcc.Dropdown(\n",
    "                id=\"forecast-horizon\",\n",
    "                options=[{\"label\": str(h), \"value\": h} for h in [6, 12, 24]],\n",
    "                value=12\n",
    "            )\n",
    "        ], style={\"width\": \"24%\", \"display\": \"inline-block\", \"marginRight\": \"1%\"}),\n",
    "\n",
    "        html.Div([\n",
    "            html.Label(\"Mode:\"),\n",
    "            dcc.RadioItems(\n",
    "                id=\"mode-switch\",\n",
    "                options=[{\"label\": \"Light\", \"value\": \"light\"}, {\"label\": \"Dark\", \"value\": \"dark\"}],\n",
    "                value=\"light\",\n",
    "                inline=True\n",
    "            )\n",
    "        ], style={\"width\": \"24%\", \"display\": \"inline-block\"})\n",
    "    ], style={\"marginBottom\": \"20px\"}),\n",
    "\n",
    "    # KPI cards\n",
    "    html.Div(id=\"kpi-cards\", style={\"display\": \"flex\", \"justifyContent\": \"space-around\", \"marginBottom\": \"20px\"}),\n",
    "\n",
    "    # Tabs\n",
    "    dcc.Tabs([\n",
    "        dcc.Tab(label=\"Sales by Region\", children=[dcc.Graph(id=\"sales-region\")]),\n",
    "        dcc.Tab(label=\"Profit by Category\", children=[dcc.Graph(id=\"profit-category\")]),\n",
    "        dcc.Tab(label=\"Sales Forecast\", children=[\n",
    "            dcc.Graph(id=\"sales-forecast\"),\n",
    "            html.Button(\"Export Forecast PNG\", id=\"export-btn\")\n",
    "        ])\n",
    "    ])\n",
    "])\n",
    "\n",
    "# ===============================\n",
    "# 5. Callback for Interactive Charts + KPIs\n",
    "# ===============================\n",
    "@app.callback(\n",
    "    Output(\"sales-region\", \"figure\"),\n",
    "    Output(\"profit-category\", \"figure\"),\n",
    "    Output(\"sales-forecast\", \"figure\"),\n",
    "    Output(\"kpi-cards\", \"children\"),\n",
    "    Input(\"region-filter\", \"value\"),\n",
    "    Input(\"category-filter\", \"value\"),\n",
    "    Input(\"forecast-horizon\", \"value\"),\n",
    "    Input(\"mode-switch\", \"value\")\n",
    ")\n",
    "def update_charts(region, category, horizon, mode):\n",
    "    # Filter data\n",
    "    dff = df.copy()\n",
    "    if region:\n",
    "        dff = dff[dff[\"Region\"] == region]\n",
    "    if category:\n",
    "        dff = dff[dff[\"Category\"] == category]\n",
    "\n",
    "    # KPI values\n",
    "    total_sales = dff[\"Sales\"].sum()\n",
    "    total_profit = dff[\"Profit\"].sum()\n",
    "    avg_order = dff[\"Sales\"].mean() if not dff.empty else 0\n",
    "\n",
    "    kpi_children = [\n",
    "        html.Div([\n",
    "            html.H4(\"Total Sales\"),\n",
    "            html.P(f\"${total_sales:,.0f}\")\n",
    "        ], style={\"border\": \"1px solid #ccc\", \"padding\": \"10px\", \"borderRadius\": \"10px\", \"width\": \"30%\", \"textAlign\": \"center\"}),\n",
    "        html.Div([\n",
    "            html.H4(\"Total Profit\"),\n",
    "            html.P(f\"${total_profit:,.0f}\")\n",
    "        ], style={\"border\": \"1px solid #ccc\", \"padding\": \"10px\", \"borderRadius\": \"10px\", \"width\": \"30%\", \"textAlign\": \"center\"}),\n",
    "        html.Div([\n",
    "            html.H4(\"Avg Order Value\"),\n",
    "            html.P(f\"${avg_order:,.2f}\")\n",
    "        ], style={\"border\": \"1px solid #ccc\", \"padding\": \"10px\", \"borderRadius\": \"10px\", \"width\": \"30%\", \"textAlign\": \"center\"})\n",
    "    ]\n",
    "\n",
    "    # Sales by Region\n",
    "    sales_region = dff.groupby(\"Region\")[\"Sales\"].sum().reset_index()\n",
    "    fig1 = px.bar(sales_region, x=\"Region\", y=\"Sales\", title=\"Total Sales by Region\")\n",
    "    if mode == \"dark\":\n",
    "        fig1.update_layout(template=\"plotly_dark\")\n",
    "\n",
    "    # Profit by Category\n",
    "    profit_category = dff.groupby(\"Category\")[\"Profit\"].sum().reset_index()\n",
    "    fig2 = px.bar(profit_category, x=\"Category\", y=\"Profit\", title=\"Total Profit by Category\")\n",
    "    if mode == \"dark\":\n",
    "        fig2.update_layout(template=\"plotly_dark\")\n",
    "\n",
    "    # Sales Forecast\n",
    "    fig3 = go.Figure()\n",
    "    actual = dff.groupby(pd.Grouper(key=\"Order_Date\", freq=\"MS\"))[[\"Sales\"]].sum().reset_index()\n",
    "    actual.columns = [\"ds\", \"y\"]\n",
    "\n",
    "    # Historical line\n",
    "    if not actual.empty:\n",
    "        fig3.add_trace(go.Scatter(x=actual[\"ds\"], y=actual[\"y\"], mode=\"lines+markers\",\n",
    "                                  name=\"Actual\", hovertemplate=\"%{x|%b %Y}: $%{y:.2f}\"))\n",
    "\n",
    "        # Scale forecast\n",
    "        scale_factor = actual[\"y\"].iloc[-1] / monthly_sales[\"y\"].iloc[-1]\n",
    "        scaled_forecast_y = global_forecast[\"yhat1\"][:horizon] * scale_factor\n",
    "        fig3.add_trace(go.Scatter(x=global_forecast[\"ds\"][:horizon], y=scaled_forecast_y,\n",
    "                                  mode=\"lines+markers\", name=\"Forecast (Scaled)\",\n",
    "                                  hovertemplate=\"%{x|%b %Y}: $%{y:.2f}\"))\n",
    "    else:\n",
    "        fig3.add_trace(go.Scatter(x=global_forecast[\"ds\"][:horizon], y=global_forecast[\"yhat1\"][:horizon],\n",
    "                                  mode=\"lines+markers\", name=\"Forecast\",\n",
    "                                  hovertemplate=\"%{x|%b %Y}: $%{y:.2f}\"))\n",
    "\n",
    "    fig3.update_layout(title=\"Sales Forecast\", xaxis_title=\"Date\", yaxis_title=\"Sales\")\n",
    "    if mode == \"dark\":\n",
    "        fig3.update_layout(template=\"plotly_dark\")\n",
    "\n",
    "    return fig1, fig2, fig3, kpi_children\n",
    "\n",
    "# ===============================\n",
    "# 6. Run App\n",
    "# ===============================\n",
    "if __name__ == \"__main__\":\n",
    "    app.run(debug=False, port=8050)\n"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python [conda env:base] *",
   "language": "python",
   "name": "conda-base-py"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12.7"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
